# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    prompt(
      text: "Have you increased the version code in Info.plist",
      boolean: true,
    )
    match(
      type: "appstore",
      git_url: "https://github.com/ReeceKidd/streakoid-certificates"
    ) 
    increment_build_number(xcodeproj: "streakoid.xcodeproj")
    build_app(workspace: "streakoid.xcworkspace", scheme: "streakoid")
    deliver(automatic_release: true, force: true, submit_for_review: true, submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: false,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    })
    notification(title: "Finished IOS Build", message: "Finished IOS Build")
  end
  error do |lane, exception, options|
    notification(title: "IOS Build Failed", message: "IOS Build Failed")
    end
end
