# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    answer = UI.select("Would you like to add a Changelog?", ["Y", "N"])
    changelog = ask('Type Changelog message:') if answer == "Y"
    match(
      type: "appstore",
      git_url: "https://github.com/ReeceKidd/streakoid-certificates"
    ) 
    increment_build_number(xcodeproj: "streakoid.xcodeproj")
    build_app(workspace: "streakoid.xcworkspace", scheme: "streakoid")
    deliver(automatic_release: true, force: true)
    notification(title: "Finished IOS Build", message: "IOS build uploaded.")
  end
  error do |lane, exception, options|
    notification(title: "IOS Build Failed", message: exception)
    end
end
