# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    # Bump version code for uploading
  increment_version_code   
  versionCode = File.read("metadata/versionCode").to_i
  versionCode = versionCode +1
  versionCodeFile = File.new("metadata/versionCode", "w")
  versionCodeFile.write(versionCode)
  versionCodeFile.close
    
  versionName ="1.0.#{versionCode}"
  versionNameFile = File.new("metadata/versionName", "w")
  versionNameFile.write(versionName)
  versionNameFile.close
  
  gradle(task: "clean")
  gradle(task: "bundleRelease", properties: { "versionName" => versionName })
  upload_to_play_store(skip_upload_apk: true)
  end
end
